lib/tartuBike_web/router.ex
defmodule TartuBikeWeb.Router do
  use TartuBikeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TartuBikeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    #plug TartuBike.Authentication, repo: TartuBike.Repo
  end

  pipeline :browser_auth do
    plug TartuBike.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TartuBikeWeb do
    pipe_through :browser

    resources "/sessions", SessionController, only: [:new, :create, :delete ]
  end

  scope "/", TartuBikeWeb do
    pipe_through [:browser, :browser_auth]

    get "/", PageController, :index
    resources "/users", UserController
    get "/popular", RouteController, :index
    get "/search", SearchController, :index
    post "/search", SearchController, :nearby
    post "/search/nearme", SearchController, :nearme
    get "/search/:station_id/show-bikes", SearchController, :showBikes
  end

  scope "/", TartuBikeWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]

    resources "/memberships", MembershipController

    get "/rent", BikeController, :rent
    post "/rent", BikeController, :rentit
    get "/book", BikeController, :book
    post "/book", BikeController, :bookit
    get "/end", BikeController, :end_ride
    post "/endit", BikeController, :endit
    resources "/reports", ReportController
    get "/usersummary", UsersummaryController, :usersummary
    get "/userusage", UsersummaryController, :userusage
    get "/ridehistory", UsersummaryController, :ridehistory
    get "/invoicehistory", UsersummaryController, :invoicehistory

    # Utility for add balance and payment
    get "/paymentservice/addBalance", PaymentserviceController, :index
    post "/paymentservice/addBalance", PaymentserviceController, :addBalance
    get "/paymentservice/issue", PaymentserviceController, :issue
    post "/paymentservice/issue", PaymentserviceController, :issueCheck
    post "/paymentservice/issuePay", PaymentserviceController, :issuePay

    get "/invoice", InvoiceController, :invoice
    get "/reciept", RecieptController, :reciept
    post "/invoicesuccess", InvoiceController, :successinvoice

  end

  # Other scopes may use custom stacks.
  # scope "/api", TartuBikeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TartuBikeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/tartuBike_web/controllers/paymentservice_controller.ex
defmodule TartuBikeWeb.PaymentserviceController do
  use TartuBikeWeb, :controller
  alias TartuBike.{Repo, Problems.Report, Invoices.Invoice}
  import Ecto.Query, only: [from: 2]

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def issue(conn, _params) do
    render(conn, "issue.html")
  end

  def issueCheck(conn, %{"ref" => ref, "bike_id" => bike_id, "fee" => fee, "charged" => _charged}) do
    user = TartuBike.Authentication.load_current_user(conn)
    query =
      from r in Report,
        where: r.reference == ^ref and r.bike_id == ^bike_id and r.user_id == ^user.id,
        select: r

    case Repo.all(query) do
      [_] ->
        invoicedate = DateTime.utc_now() |> DateTime.truncate(:second)
        Repo.insert!(%Invoice{description: "fee: €#{fee}", invoice_date: invoicedate,  amount: Decimal.new(fee), user_id: user.id})

        updateBalance(Decimal.new(fee), conn)
        conn
          |> put_flash(:info, "You have successfully ended the ride; Fee: €#{fee}")
          |> redirect(to: Routes.invoice_path(conn, :invoice))
      _ ->
        conn
          |> put_flash(:error, "No report issues found! Bike id: #{bike_id}")
          |> render("issue.html")
    end
  end

  def issuePay(conn, %{"fee" => fee, "charged" => charged}) do
    user = TartuBike.Authentication.load_current_user(conn)
    amount = Decimal.add(Decimal.new(fee), Decimal.new(charged))

    invoicedate = DateTime.utc_now() |> DateTime.truncate(:second)
    Repo.insert!(%Invoice{description: "fee: €#{fee} with delay or missing bike charged: €#{charged}", invoice_date: invoicedate,  amount: amount, user_id: user.id})

    updateBalance(amount, conn)
    conn
    |> put_flash(:info, "You have successfully ended the ride; Fee: €#{fee} Charged: €#{charged}")
    |> redirect(to: Routes.invoice_path(conn, :invoice))
  end

  def addBalance(conn, %{"amount" => amount}) do
    amt = Decimal.new(amount)
    updateBalance(amt, conn, false)
    conn
    |> put_flash(:info, "Balance added")
    |> redirect(to: Routes.page_path(conn, :index))
  end

  defp updateBalance(amount, conn, sub \\ true) do
    u = TartuBike.Authentication.load_current_user(conn)
    balance = if sub, do: Decimal.sub(u.balance, amount), else: Decimal.add(u.balance, amount)
    u |> Ecto.Changeset.change(balance: balance)
      |> Repo.update!
  end

end

lib/tartuBike_web/views/paymentservice_view.ex
defmodule TartuBikeWeb.PaymentserviceView do
  use TartuBikeWeb, :view
end

lib/tartuBike_web/templates/paymentservice/index.html.heex
<h1>Add balance</h1>

<%= form_for @conn, Routes.paymentservice_path(@conn, :addBalance) , fn f -> %>
    <div class="form-group">
        <label>Amount: </label>
        <%= number_input f, :amount, class: "form-control", required: "required", min: "1", value: "10" %>
        <%= submit "Submit", id: "balance-submit", class: "btn btn-primary" %>
    </div>
<% end %>

lib/tartuBike_web/templates/paymentservice/issue.html.heex
<%= form_for @conn, Routes.paymentservice_path(@conn, :issue) , fn f -> %>
    <div class="form-group">
    Please report a technical problem to avoid charged from returning delay or bike missing fee of
    <h2 style="color:red">€ <%=f.params["charged"]%></h2>
        <label>Issue Reference number (X-00000000000): </label>
        <%= text_input f, :ref, class: "form-control", required: "required" %>
        <%= hidden_input f, :bike_id, class: "form-control", required: "required" %>
        <%= hidden_input f, :fee, class: "form-control", required: "required" %>
        <%= hidden_input f, :charged, class: "form-control" %>
        <%= submit "Submit", id: "report-id-submit", class: "btn btn-primary" %>
    </div>
<% end %>
<%= link "Report issue >", to: "/reports/new", class: "button button-outline", target: "_blank" %>
<hr/>
<%= form_for @conn, Routes.paymentservice_path(@conn, :issuePay) , fn f -> %>
    <div class="form-group">
        <%= hidden_input f, :fee, class: "form-control" %>
        <%= hidden_input f, :charged, class: "form-control" %>
        <p>I am willing to pay fee</p>
        <%= submit "pay € #{f.params["charged"]}", id: "fee-submit", class: "btn btn-primary alert-danger" %>
    </div>
<% end %>
<br/>